create sequence seq_refresh_token
    increment by 5;

alter sequence seq_refresh_token owner to postgres;

create sequence user_id_seq;

alter sequence user_id_seq owner to postgres;

create table payment
(
    id             bigint generated by default as identity
        primary key,
    amount         double precision not null,
    created_at     timestamp(6)     not null,
    payed_at       timestamp(6),
    payment_status varchar(255)     not null
        constraint payment_payment_status_check
            check ((payment_status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'REJECTED'::character varying, 'APPROVED'::character varying])::text[]))
    );

alter table payment
    owner to postgres;

create table _user_
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) not null,
    email         varchar(255) not null,
    first_name    varchar(255),
    global_role   varchar(255) not null
        constraint _user__global_role_check
            check ((global_role)::text = ANY ((ARRAY ['USER'::character varying, 'ADMIN'::character varying])::text[])),
    is_landlord   boolean,
    is_renter     boolean,
    last_name     varchar(255),
    password_hash varchar(255) not null,
    patronymic    varchar(255),
    phone_number  varchar(20),
    updated_at    timestamp(6) not null,
    username      varchar(255) not null
);

alter table _user_
    owner to postgres;

create table chat
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    user1_id_id bigint       not null
        constraint fktgobnk4vrlcnm98lhw5dg8o5s
            references _user_,
    user2_id_id bigint       not null
        constraint fk3lc65cxbwgsjiv5nm283rikoo
            references _user_
);

alter table chat
    owner to postgres;

create table contact
(
    id           bigint generated by default as identity
        primary key,
    contact      varchar(255) not null,
    contact_type varchar(255) not null,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    user_id_id   bigint       not null
        constraint fknjlfj15huwbnw3byj4j2xtqm5
            references _user_
);

alter table contact
    owner to postgres;

create table message
(
    id           bigint generated by default as identity
        primary key,
    message      varchar(255) not null,
    timestamp    timestamp(6) not null,
    chat_id      bigint       not null
        constraint fkmejd0ykokrbuekwwgd5a5xt8a
            references chat,
    sender_id_id bigint       not null
        constraint fk7xgmqah0yxqaa24cciyhiwl7w
            references _user_
);

alter table message
    owner to postgres;

create table property
(
    id             bigint generated by default as identity
        primary key,
    available      boolean,
    city           varchar(255) not null,
    country        varchar(255) not null,
    created_at     timestamp(6) not null,
    description    varchar(255),
    latitude       double precision,
    longitude      double precision,
    nearest_subway varchar(255),
    postal_code    varchar(255) not null,
    price          real         not null,
    region         varchar(255) not null,
    square         real         not null,
    street         varchar(255) not null,
    title          varchar(255) not null,
    type           varchar(255) not null,
    updated_at     timestamp(6) not null,
    user_id        bigint       not null
        constraint fk62g66ps35hh3pn0fu3swbhjov
            references _user_,
    avg_rating     double precision,
    rating_sum     integer,
    total_reviews  integer
);

alter table property
    owner to postgres;

create table booking
(
    id             bigint generated by default as identity
        primary key,
    booking_status varchar(255)     not null
        constraint booking_booking_status_check
            check ((booking_status)::text = ANY
        ((ARRAY ['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'REJECTED'::character varying])::text[])),
    created_at     timestamp(6)     not null,
    details        varchar(255),
    end_date       date             not null,
    guests_count   integer,
    start_date     date             not null,
    total_price    double precision not null,
    property_id    bigint           not null
        constraint fkbcgr7a3utjxb9n6ltvw0w6xqs
            references property,
    renter_id      bigint           not null
        constraint fk2mbjf9vc5ch7skap2yfgkav80
            references _user_,
    payment_id     bigint
        constraint ukxcv4bjb631pysj91ybp40vpo
            unique
        constraint fk70t92vvx289ayx2hq2v4hdcjl
            references payment
);

alter table booking
    owner to postgres;

create table property_image
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null,
    url         varchar(255),
    property_id bigint       not null
        constraint fk8myddv2ina4svuo189ju03v9o
            references property
);

alter table property_image
    owner to postgres;

create table review
(
    id             bigint generated by default as identity
        primary key,
    comment        varchar(255),
    created_at     timestamp(6) not null,
    rating         integer      not null,
    updated_at     timestamp(6) not null,
    property_id_id bigint       not null
        constraint fk6df8rcbya9nwn24fu461xokkp
            references property,
    user_id_id     bigint       not null
        constraint fkq7behv4inlscrfyh544x1dhgj
            references _user_
);

alter table review
    owner to postgres;

create table amenity
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
        constraint uktojea3b0gq1a796dt56ml4xdr
            unique
);

alter table amenity
    owner to postgres;

create table property_amenity_link
(
    property_id bigint not null
        constraint fkdgq2bs3l5oa9pci3dkdl97s2o
            references property,
    amenity_id  bigint not null
        constraint fkpovpbqro6xbei3l1kklsmjk1u
            references amenity,
    primary key (property_id, amenity_id)
);

alter table property_amenity_link
    owner to postgres;

create table refresh_token
(
    id         bigint       not null
        primary key,
    expires_at timestamp(6) not null,
    revoked    boolean,
    token      varchar(255) not null
        constraint ukr4k4edos30bx9neoq81mdvwph
            unique,
    user_id    bigint       not null
        constraint fkgb099hrv44qdetxf76qsh02dx
            references _user_
);

alter table refresh_token
    owner to postgres;

